[[item]]
name = "代数结构"
dir = "algebra"

[[item]]
name = "图论"
dir = "graph"

[[item]]
name = "网络流"
dir = "flow"

[[item]]
name = "数论"
dir = "number_theory"

[[item]]
name = "组合数学"
dir = "combinatorics"

[[item]]
name = "数据结构"
dir = "data_structure"

[[item]]
name = "字符串"
dir = "string"

[[item]]
name = "杂项"
dir = "misc"
