[[item]]
name = "Base"
file = "base.hpp"

[[item]]
name = "最短路"
dir = "shortest_path"

[[item]]
name = "拓扑排序"
file = "toposort.hpp"

[[item]]
name = "欧拉通路/回路"
file = "eulerian.hpp"
description = "eulerian.typ"

[[item]]
name = "最小生成树"
dir = "mst"

[[item]]
name = "连通性"
dir = "components"

[[item]]
name = "树链剖分"
file = "hld.hpp"

[[item]]
name = "LCA"
file = "lca.hpp"

[[item]]
name = "树上倍增"
file = "tree_lifting.hpp"

[[item]]
name = "虚树"
file = "virtual_tree.hpp"

[[item]]
name = "2-SAT"
file = "twosat.hpp"
description = "twosat.typ"
