[[item]]
name = "最短路"
dir = "shortest_path"

[[item]]
name = "最小生成树"
dir = "mst"

[[item]]
name = "连通性"
dir = "components"

[[item]]
name = "树链剖分"
file = "hld.hpp"

[[item]]
name = "LCA"
file = "lca.hpp"

[[item]]
name = "虚树"
file = "virtual_tree.hpp"

[[item]]
name = "2-SAT"
file = "twosat.hpp"
