[[item]]
name = "Manacher"
file = "manacher.hpp"

[[item]]
name = "KMP"
file = "kmp.hpp"

[[item]]
name = "Trie"
file = "trie.hpp"

[[item]]
name = "01-Trie"
file = "01Trie.hpp"

[[item]]
name = "Z函数"
file = "z_algo.hpp"

[[item]]
name = "AC自动机"
file = "aho_corasick.hpp"
