[[item]]
name = "扩展欧几里得算法"
file = "exgcd.hpp"

[[item]]
name = "线性筛"
file = "sieve.hpp"

[[item]]
name = "莫比乌斯反演"
file = "mobius.hpp"
description = "mobius.typ"

[[item]]
name = "欧拉函数"
file = "euler.hpp"
description = "euler.typ"

[[item]]
name = "Miller-Rabin"
file = "miller_rabin.hpp"

[[item]]
name = "Pollard-Rho"
file = "pollard.hpp"

[[item]]
name = "约数构造"
file = "divisors.hpp"