[[item]]
name = "扩展欧几里得算法"
file = "exgcd.hpp"

[[item]]
name = "线性筛"
file = "sieve.hpp"

[[item]]
name = "莫比乌斯反演"
file = "mobius.hpp"
tex = "mobius.tex"

[[item]]
name = "欧拉函数"
file = "euler.hpp"
tex = "euler.tex"
