[[item]]
name = "矩阵"
file = "matrix.hpp"

[[item]]
name = "高斯消元"
file = "gauss.hpp"

[[item]]
name = "矩阵秩"
file = "matrix_rank.hpp"

[[item]]
name = "逆矩阵"
file = "matrix_inv.hpp"

[[item]]
name = "异或线性基"
file = "basis.hpp"
