[[item]]
name = "线段树"
dir = "segment_tree"

[[item]]
name = "树状数组"
dir = "fenwick"

[[item]]
name = "并查集"
file = "dsu.hpp"

[[item]]
name = "稀疏表"
file = "sparse_table.hpp"

[[item]]
name = "01-Trie"
file = "binary_trie.hpp"

[[item]]
name = "笛卡尔树"
file = "cartesian_tree.hpp"
